language: c

compiler:
    - gcc

matrix:
  fast_finish: true
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
         - MATRIX_EVAL="CC=gcc-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir bins
    - mkdir -p ./build
    - cd ./build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . --target all
