name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # configure cmake project
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # build project
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # create directory for the results
    - name: Create Directory
      working-directory: ${{github.workspace}}/bins
      run: mkdir -p results
    
    # run tests
    - name: Test
      working-directory: ${{github.workspace}}/bins
      run: ctest -C ${{env.BUILD_TYPE}}
      
